vich_uploader:
    db_driver: orm
    mappings:
        cover_image_user:
            uri_prefix: /uploads/image_user #construire les liens quand il va recuperer au niveaux du front , le prefix des liens
            upload_destination: '%kernel.project_dir%/public/uploads/image_user' #deposer les fichiers
            delete_on_remove: true
            delete_on_update: true
