vich_uploader:
    db_driver: orm
    mappings:
        voyage_image:
            uri_prefix:  '%app.path.voyage_image%'
            upload_destination: '%kernel.project_dir%/public/uploads/voyage_image' #deposer les fichiers
            delete_on_remove: true
            delete_on_update: true
